
// This file was auto-generated by ML.NET Model Builder. 

using BoardMemberResponse_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
BoardMemberResponse.ModelInput sampleData = new BoardMemberResponse.ModelInput()
{
    Text = @"Can I get more information about the product?",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Text with predicted Text from sample data...\n\n");


Console.WriteLine($"Text: {@"Unfortunately, we cannot accept your request at this time."}");
Console.WriteLine($"Label: {@"REJECTION"}");


var sortedScoresWithLabel = BoardMemberResponse.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

