
// This file was auto-generated by ML.NET Model Builder. 

using BoardMemberRejectionModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
BoardMemberRejectionModel.ModelInput sampleData = new BoardMemberRejectionModel.ModelInput()
{
    Text = @"Sorry, but your submission does not meet our requirements.",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


Console.WriteLine($"Text: {@"Sorry, but your submission does not meet our requirements."}");
Console.WriteLine($"Label: {@"REJECTION"}");


var sortedScoresWithLabel = BoardMemberRejectionModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

