
// This file was auto-generated by ML.NET Model Builder. 

using IARecognizeAnswers;

// Create single instance of sample data from first line of dataset for model input
BoardApprovalModel.ModelInput sampleData = new BoardApprovalModel.ModelInput()
{
    Text = @"Unfortunately, we cannot accept your request at this time.",
};

//Load sample data
var sampleDataT = new BoardRejectionModel.ModelInput()
{
    Text = @"Sorry, but your submission does not meet our requirements.",
};


Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


Console.WriteLine($"Text: {@"Unfortunately, we cannot accept your request at this time."}");
Console.WriteLine($"Label: {@"REJECTION"}");


var sortedScoresWithLabel = BoardApprovalModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

